version: '3'
services:
    nginx:
        container_name: some-nginx
        image: nginx:1.13
        restart: always
        ports:
        - 80:80
        - 443:443
        volumes:
        - ./nginx/conf.d:/etc/nginx/conf.d
        depends_on:
        - demo2
    mysql:
        container_name: my-mysql
        image: mysql/mysql-server:5.7
        environment:
            MYSQL_DATABASE: test
            MYSQL_ROOT_PASSWORD: root
            MYSQL_ROOT_HOST: '%'
        ports:
        - "3306:3306"
        restart: always
    demo2:
        restart: always
        build: ./demo2
        working_dir: /demo2
        volumes:
          - ./demo2:/demo2
          - ~/.m2:/root/.m2
        expose:
          - "8080"
        command: mvn clean spring-boot:run
        depends_on:
          - mysql